In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris_dataset.csv")

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

        target  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [6]:
df.sample(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
45                 4.8               3.0                1.4               0.3   
109                7.2               3.6                6.1               2.5   
94                 5.6               2.7                4.2               1.3   
97                 6.2               2.9                4.3               1.3   
19                 5.1               3.8                1.5               0.3   
133                6.3               2.8                5.1               1.5   
90                 5.5               2.6                4.4               1.2   
60                 5.0               2.0                3.5               1.0   
36                 5.5               3.5                1.3               0.2   
88                 5.6               3.0                4.1               1.3   

              target  
45       Iris-setosa  
109   Iris-virginica  
94   Iris-versicolor  
97   Iris-versicolor  
19       Iris-setosa  
133   Iris-virginica  
90   Iris-versicolor  
60   Iris-versicolor  
36       Iris-setosa  
88   Iris-versicolor

In [7]:
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

             target  
0    

In [8]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [9]:

df.shape

(150, 5)

In [10]:
print (df[10:21])

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   
15                5.7               4.4                1.5               0.4   
16                5.4               3.9                1.3               0.4   
17                5.1               3.5                1.4               0.3   
18                5.7               3.8                1.7               0.3   
19                5.1               3.8                1.5               0.3   
20                5.4               3.4                1.7               0.2   

         target  
10  Iris-setosa  
11 

In [11]:
df["target"]=df["target"].replace("Iris-setosa",0)
df["target"]=df["target"].replace("Iris-versicolor",1)
df["target"]=df["target"].replace("Iris-virginica",2)

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [13]:
X=df.values[:,:4]
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
y=df.values[:,4]
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state= 100)
print(X_train.shape)
X_test.shape


(105, 4)


(45, 4)

In [18]:
import keras
from keras.models import Sequential,model_from_json
from keras.layers import Dense
from keras.optimizers import RMSprop
from tensorflow.keras.optimizers import Adam

In [20]:
first_layer_size=32
num_classes=3
model = Sequential()
model.add(Dense(first_layer_size, activation ='sigmoid', input_shape=(4,)))
model.add(Dense(32, activation='sigmoid'))
model.add(Dense(32, activation='sigmoid'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 32)                1056      
                                                                 
 dense_3 (Dense)             (None, 3)                 99        
                                                                 
Total params: 2371 (9.26 KB)
Trainable params: 2371 (9.26 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:

print(y_test)
y_train = keras.utils.to_categorical(y_train, num_classes ,dtype ="float")
y_test = keras.utils.to_categorical(y_test, num_classes, dtype ="float")
y_test

[2. 0. 2. 0. 2. 2. 0. 0. 2. 0. 0. 2. 0. 0. 2. 1. 1. 1. 2. 2. 2. 0. 2. 0.
 1. 2. 1. 0. 1. 2. 1. 1. 2. 0. 0. 1. 0. 1. 2. 2. 0. 1. 2. 2. 0.]


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [22]:
model.compile(loss='categorical_crossentropy', optimizer=RMSprop(), metrics=['accuracy'])

In [25]:
import numpy as np
X_train = np.asarray(X_train).astype('float32')
X_test = np.asarray(X_test).astype('float32')

history = model.fit(X_train,y_train,
                    batch_size=10,
                    epochs=100,
                    verbose=1)

Epoch 1/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0742 - accuracy: 0.9714
Epoch 2/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0746 - accuracy: 0.9714
Epoch 3/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0695 - accuracy: 0.9619
Epoch 4/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0715 - accuracy: 0.9714
Epoch 5/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0740 - accuracy: 0.9810
Epoch 6/100
11/11 [==============================] - 0s 2ms/step - loss: 0.0741 - accuracy: 0.9619
Epoch 7/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0819 - accuracy: 0.9524
Epoch 8/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0721 - accuracy: 0.9619
Epoch 9/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0736 - accuracy: 0.9714
Epoch 10/100
11/11 [==============================] - 0s 3ms/step - loss: 0.0742 - accuracy: 0.9810
Epoch 11/

In [26]:
# Write the testing input and output variables
score = model.evaluate(X_test, y_test, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

2/2 [==============================] - 0s 12ms/step - loss: 0.0155 - accuracy: 1.0000
Test loss: 0.015525494702160358
Test accuracy: 1.0


In [27]:
prediction = model.predict(X_test[1:25])

print('Prediction\n',prediction)
print('\nThresholded output\n',(prediction > 0.5).astype(int))
#prediction_new = keras.utils.to_categorical(prediction, num_classes, dtype ="float")
#print(prediction_new)



1/1 [==============================] - 0s 155ms/step
Prediction
 [[9.99823093e-01 1.76888439e-04 1.00092244e-07]
 [4.41412373e-09 9.83400154e-04 9.99016464e-01]
 [9.99873161e-01 1.26748753e-04 7.36153183e-08]
 [7.59210081e-07 1.11022703e-01 8.88976514e-01]
 [1.10583169e-08 2.43954477e-03 9.97560322e-01]
 [9.99872208e-01 1.27820720e-04 7.41713961e-08]
 [9.99819517e-01 1.80485527e-04 1.01945581e-07]
 [1.00814248e-07 1.86237991e-02 9.81376052e-01]
 [9.99802351e-01 1.97461748e-04 1.10792882e-07]
 [9.99850988e-01 1.49016851e-04 8.54712567e-08]
 [2.78557160e-08 5.75001957e-03 9.94249880e-01]
 [9.99805212e-01 1.94791413e-04 1.09434971e-07]
 [9.99850273e-01 1.49674903e-04 8.57857572e-08]
 [3.78199729e-08 7.63174426e-03 9.92368221e-01]
 [4.20850956e-05 9.99189913e-01 7.68010679e-04]
 [5.34391475e-05 9.99439836e-01 5.06638549e-04]
 [7.09453616e-06 6.87605441e-01 3.12387437e-01]
 [7.22994908e-09 1.62035355e-03 9.98379529e-01]
 [3.54054990e-08 7.20465276e-03 9.92795289e-01]
 [6.43562146e-08 1.2473

In [28]:
# check that it has worked right or not
#print(X_test[23:25])
print(y_test[1:25])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
